# Generated by Django 3.1.4 on 2021-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pappu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
            options={
                'db_table': 'bank',
            },
        ),
    ]
