# Generated by Django 3.1.4 on 2021-02-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pappu', '0002_bankaccount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank',
        ),
    ]
