# Generated by Django 3.1.4 on 2021-02-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pappu', '0003_auto_20210208_1403'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankaccount',
            table='newbank',
        ),
    ]
